dataset:
  RESIZE_SHAPE: (96, 96)
  AUGMENTATION:
    CROP_SCALE: (0.7, 0.1)
    H_FLIP_PROB : 0.5
    ROTATION_RANGE: 25
    BLUR_KERNEL_SIZE: 3

MODEL:
  NAME: EFFICIENT_NET_SMALL
  NUM_CLASSES: 10
TRAINING:
  LR: 0.0001
  OPTIMIZER: ADAM

